In [7]:
import os
os.environ["USE_TF"] = "0"

In [1]:
import pandas as pd
from transformers import pipeline

c:\Users\User\dev\training_model\.venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

**Preprocessing**

In [2]:
path = "../gdelt_gold_news_dataset.csv"

df = pd.read_csv(path)

df.head()

       date                                               text
0  20151227  Here's a summary of gold-related news based on...
1  20151228  Several reports discuss gold smuggling attempt...
2  20151229  Several reports discuss gold smuggling attempt...
3  20151230  Here's a summary of gold market news from the ...
4  20151231  Here's a summary of gold market news from the ...

In [3]:
df["date"] = pd.to_datetime(df["date"], format="%Y%m%d")
df = df.sort_values("date")

In [4]:
df.head()

        date                                               text
0 2015-12-27  Here's a summary of gold-related news based on...
1 2015-12-28  Several reports discuss gold smuggling attempt...
2 2015-12-29  Several reports discuss gold smuggling attempt...
3 2015-12-30  Here's a summary of gold market news from the ...
4 2015-12-31  Here's a summary of gold market news from the ...

In [5]:
df.tail()

           date                                               text
3490 2025-08-06  Gold prices are rising due to concerns over po...
3491 2025-08-07  Gold prices are rising due to concerns over po...
3492 2025-08-08  Gold futures experienced a surge to a record h...
3493 2025-08-09  Gold futures experienced a surge to a record h...
3494 2025-08-10  Gold futures experienced volatility due to con...

**Sentiment Analysis**

In [9]:
classifier = pipeline(
    "text-classification",
    model="mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis",
    tokenizer="mrm8488/distilroberta-finetuned-financial-news-sentiment-analysis"
)

WARNING:tensorflow:From c:\Users\User\dev\training_model\.venv\Lib\site-packages\tf_keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Device set to use cpu

In [10]:
df["sentiment"] = df["text"].apply(lambda x: classifier(x)[0]['label'])

In [11]:
df.head()

        date                                               text sentiment
0 2015-12-27  Here's a summary of gold-related news based on...  negative
1 2015-12-28  Several reports discuss gold smuggling attempt...  positive
2 2015-12-29  Several reports discuss gold smuggling attempt...  positive
3 2015-12-30  Here's a summary of gold market news from the ...  positive
4 2015-12-31  Here's a summary of gold market news from the ...  positive

In [12]:
path = "../gdelt_gold_news_sentiments.csv"
df.to_csv(path, index=False)