In [9]:
import joblib
import pandas as pd
from statsmodels.tsa.stattools import adfuller
from sklearn.preprocessing import MinMaxScaler

In [3]:
path = "gold_data.csv"
df = pd.read_csv(path)
df.head()

,Date,Close,Crude_Oil,Inflation,Interest_Rate,USD_EUR,USD_JPY
0,2019-01-02,1281.000000,59.41,252.561,2.4,1.1357,109.22
1,2019-01-03,1291.800049,59.41,252.561,2.4,1.1399,108.07
2,2019-01-04,1282.699951,59.41,252.561,2.4,1.1410,108.29
3,2019-01-07,1286.800049,59.41,252.561,2.4,1.1468,108.62
4,2019-01-08,1283.199951,59.41,252.561,2.4,1.1444,108.57

In [4]:
df = df.sort_values('Date').reset_index(drop=True)

In [6]:
feature_cols = ['Crude_Oil', 'Inflation', 'Interest_Rate', 'USD_EUR', 'USD_JPY']
target_col = ['Close']

feature_scaler = MinMaxScaler()
target_scaler = MinMaxScaler()

df_features_scaled = pd.DataFrame(
    feature_scaler.fit_transform(df[feature_cols]),
    columns=feature_cols,
    index=df.index
)

df_target_scaled = pd.DataFrame(
    target_scaler.fit_transform(df[target_col]),
    columns=target_col,
    index=df.index
)

In [7]:
df_scaled = pd.concat([df['Date'], df_features_scaled, df_target_scaled], axis=1)
df_scaled.head()

,Date,Crude_Oil,Inflation,Interest_Rate,USD_EUR,USD_JPY,Close
0,2019-01-02,0.393271,0.0,0.445076,0.649869,0.113157,0.005412
1,2019-01-03,0.393271,0.0,0.445076,0.665547,0.093734,0.010408
2,2019-01-04,0.393271,0.0,0.445076,0.669653,0.097450,0.006198
3,2019-01-07,0.393271,0.0,0.445076,0.691303,0.103023,0.008095
4,2019-01-08,0.393271,0.0,0.445076,0.682344,0.102179,0.006429

In [8]:
path = 'gold_data_scaled.csv'
df_scaled.to_csv(path, index=False)

In [11]:
joblib.dump( feature_scaler, 'scalers/feature_scaler.pkl')

['scalers/feature_scaler.pkl']

In [12]:
joblib.dump( target_scaler, 'scalers/target_scaler.pkl')

['scalers/target_scaler.pkl']